#!/usr/bin/env bash
# This script kills the 7-highlander process using SIGKILL (signal 9)

# Find the PID(s) of 7-highlander process(es)
pids=$(pgrep -f 7-highlander)

# Send SIGKILL to each PID found
if [ -n "$pids" ]; then
  kill -9 $pids
fi
